name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout {{cookiecutter.repo_name}}
      uses: actions/checkout@v3

    - name: Set up Python {{cookiecutter.python_version_number}}
      uses: actions/setup-python@v3
      with:
        python-version: {{cookiecutter.python_version_number}}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install black flake8 mypy
        python3 -m pip install pylint coverage
        python3 -m pip install -r requirements.txt

    - name: Analyse code with pylint
      run: |
        pylint $(git ls-files '*.py')

    - name: Run tests with pytest
      run: |
        coverage run -m pytest